// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230623220108_AddImageAndFilms")]
    partial class AddImageAndFilms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("API.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "opening_crawl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeId = 4,
                            OpeningCrawl = "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
                            Title = "A New Hope"
                        },
                        new
                        {
                            Id = 2,
                            EpisodeId = 5,
                            OpeningCrawl = "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space...",
                            Title = "The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 3,
                            EpisodeId = 6,
                            OpeningCrawl = "Luke Skywalker has returned to\r\nhis home planet of Tatooine in\r\nan attempt to rescue his\r\nfriend Han Solo from the\r\nclutches of the vile gangster\r\nJabba the Hutt.\r\n\r\nLittle does Luke know that the\r\nGALACTIC EMPIRE has secretly\r\nbegun construction on a new\r\narmored space station even\r\nmore powerful than the first\r\ndreaded Death Star.\r\n\r\nWhen completed, this ultimate\r\nweapon will spell certain doom\r\nfor the small band of rebels\r\nstruggling to restore freedom\r\nto the galaxy...",
                            Title = "Return of the Jedi"
                        },
                        new
                        {
                            Id = 4,
                            EpisodeId = 1,
                            OpeningCrawl = "Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....",
                            Title = "The Phantom Menace"
                        },
                        new
                        {
                            Id = 5,
                            EpisodeId = 2,
                            OpeningCrawl = "There is unrest in the Galactic\r\nSenate. Several thousand solar\r\nsystems have declared their\r\nintentions to leave the Republic.\r\n\r\nThis separatist movement,\r\nunder the leadership of the\r\nmysterious Count Dooku, has\r\nmade it difficult for the limited\r\nnumber of Jedi Knights to maintain \r\npeace and order in the galaxy.\r\n\r\nSenator Amidala, the former\r\nQueen of Naboo, is returning\r\nto the Galactic Senate to vote\r\non the critical issue of creating\r\nan ARMY OF THE REPUBLIC\r\nto assist the overwhelmed\r\nJedi....",
                            Title = "Attack of the Clones"
                        },
                        new
                        {
                            Id = 6,
                            EpisodeId = 3,
                            OpeningCrawl = "War! The Republic is crumbling\r\nunder attacks by the ruthless\r\nSith Lord, Count Dooku.\r\nThere are heroes on both sides.\r\nEvil is everywhere.\r\n\r\nIn a stunning move, the\r\nfiendish droid leader, General\r\nGrievous, has swept into the\r\nRepublic capital and kidnapped\r\nChancellor Palpatine, leader of\r\nthe Galactic Senate.\r\n\r\nAs the Separatist Droid Army\r\nattempts to flee the besieged\r\ncapital with their valuable\r\nhostage, two Jedi Knights lead a\r\ndesperate mission to rescue the\r\ncaptive Chancellor....",
                            Title = "Revenge of the Sith"
                        });
                });

            modelBuilder.Entity("API.Entities.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cargo_capacity");

                    b.Property<string>("Consumables")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cost_in_credits");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crew")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("HyperdriveRating")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hyperdrive_rating");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("MGLT")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "MGLT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "max_atmosphering_speed");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passengers")
                        .HasColumnType("TEXT");

                    b.Property<string>("StarshipClass")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "starship_class");

                    b.HasKey("Id");

                    b.ToTable("Starships");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CargoCapacity = "3000000",
                            Consumables = "1 year",
                            CostInCredits = "3500000",
                            Created = new DateTime(2014, 12, 10, 14, 20, 33, 369, DateTimeKind.Unspecified),
                            Crew = "30-165",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 867, DateTimeKind.Unspecified),
                            HyperdriveRating = "2.0",
                            Length = "150",
                            MGLT = "60",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxAtmospheringSpeed = "950",
                            Model = "CR90 corvette",
                            Name = "CR90 corvette",
                            Passengers = "600",
                            StarshipClass = "corvette"
                        },
                        new
                        {
                            Id = 3,
                            CargoCapacity = "36000000",
                            Consumables = "2 years",
                            CostInCredits = "150000000",
                            Created = new DateTime(2014, 12, 10, 15, 8, 19, 848, DateTimeKind.Unspecified),
                            Crew = "47,060",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 870, DateTimeKind.Unspecified),
                            HyperdriveRating = "2.0",
                            Length = "1,600",
                            MGLT = "60",
                            Manufacturer = "Kuat Drive Yards",
                            MaxAtmospheringSpeed = "975",
                            Model = "Imperial I-class Star Destroyer",
                            Name = "Star Destroyer",
                            Passengers = "n/a",
                            StarshipClass = "Star Destroyer"
                        },
                        new
                        {
                            Id = 5,
                            CargoCapacity = "180000",
                            Consumables = "1 month",
                            CostInCredits = "240000",
                            Created = new DateTime(2014, 12, 10, 15, 48, 0, 586, DateTimeKind.Unspecified),
                            Crew = "5",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 873, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Length = "38",
                            MGLT = "70",
                            Manufacturer = "Sienar Fleet Systems, Cyngus Spaceworks",
                            MaxAtmospheringSpeed = "1000",
                            Model = "Sentinel-class landing craft",
                            Name = "Sentinel-class landing craft",
                            Passengers = "75",
                            StarshipClass = "landing craft"
                        },
                        new
                        {
                            Id = 9,
                            CargoCapacity = "1000000000000",
                            Consumables = "3 years",
                            CostInCredits = "1000000000000",
                            Created = new DateTime(2014, 12, 10, 16, 36, 50, 509, DateTimeKind.Unspecified),
                            Crew = "342,953",
                            Edited = new DateTime(2014, 12, 20, 21, 26, 24, 783, DateTimeKind.Unspecified),
                            HyperdriveRating = "4.0",
                            Length = "120000",
                            MGLT = "10",
                            Manufacturer = "Imperial Department of Military Research, Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "DS-1 Orbital Battle Station",
                            Name = "Death Star",
                            Passengers = "843,342",
                            StarshipClass = "Deep Space Mobile Battlestation"
                        },
                        new
                        {
                            Id = 10,
                            CargoCapacity = "100000",
                            Consumables = "2 months",
                            CostInCredits = "100000",
                            Created = new DateTime(2014, 12, 10, 16, 59, 45, 94, DateTimeKind.Unspecified),
                            Crew = "4",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 880, DateTimeKind.Unspecified),
                            HyperdriveRating = "0.5",
                            Length = "34.37",
                            MGLT = "75",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxAtmospheringSpeed = "1050",
                            Model = "YT-1300 light freighter",
                            Name = "Millennium Falcon",
                            Passengers = "6",
                            StarshipClass = "Light freighter"
                        },
                        new
                        {
                            Id = 11,
                            CargoCapacity = "110",
                            Consumables = "1 week",
                            CostInCredits = "134999",
                            Created = new DateTime(2014, 12, 12, 11, 0, 39, 817, DateTimeKind.Unspecified),
                            Crew = "2",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 883, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Length = "14",
                            MGLT = "80",
                            Manufacturer = "Koensayr Manufacturing",
                            MaxAtmospheringSpeed = "1000km",
                            Model = "BTL Y-wing",
                            Name = "Y-wing",
                            Passengers = "0",
                            StarshipClass = "assault starfighter"
                        },
                        new
                        {
                            Id = 12,
                            CargoCapacity = "110",
                            Consumables = "1 week",
                            CostInCredits = "149999",
                            Created = new DateTime(2014, 12, 12, 11, 19, 5, 340, DateTimeKind.Unspecified),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 886, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Length = "12.5",
                            MGLT = "100",
                            Manufacturer = "Incom Corporation",
                            MaxAtmospheringSpeed = "1050",
                            Model = "T-65 X-wing",
                            Name = "X-wing",
                            Passengers = "0",
                            StarshipClass = "Starfighter"
                        },
                        new
                        {
                            Id = 13,
                            CargoCapacity = "150",
                            Consumables = "5 days",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 12, 11, 21, 32, 991, DateTimeKind.Unspecified),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 889, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Length = "9.2",
                            MGLT = "105",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "1200",
                            Model = "Twin Ion Engine Advanced x1",
                            Name = "TIE Advanced x1",
                            Passengers = "0",
                            StarshipClass = "Starfighter"
                        },
                        new
                        {
                            Id = 15,
                            CargoCapacity = "250000000",
                            Consumables = "6 years",
                            CostInCredits = "1143350000",
                            Created = new DateTime(2014, 12, 15, 12, 31, 42, 547, DateTimeKind.Unspecified),
                            Crew = "279,144",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 893, DateTimeKind.Unspecified),
                            HyperdriveRating = "2.0",
                            Length = "19000",
                            MGLT = "40",
                            Manufacturer = "Kuat Drive Yards, Fondor Shipyards",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "Executor-class star dreadnought",
                            Name = "Executor",
                            Passengers = "38000",
                            StarshipClass = "Star dreadnought"
                        },
                        new
                        {
                            Id = 17,
                            CargoCapacity = "19000000",
                            Consumables = "6 months",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 34, 52, 264, DateTimeKind.Utc),
                            Crew = "6",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 895, DateTimeKind.Utc),
                            HyperdriveRating = "4.0",
                            Length = "90",
                            MGLT = "20",
                            Manufacturer = "Gallofree Yards, Inc.",
                            MaxAtmospheringSpeed = "650",
                            Model = "GR-75 medium transport",
                            Name = "Rebel transport",
                            Passengers = "90",
                            StarshipClass = "Medium transport"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
