// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("API.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "episode_id");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "opening_crawl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeId = 4,
                            OpeningCrawl = "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
                            Title = "A New Hope"
                        },
                        new
                        {
                            Id = 2,
                            EpisodeId = 5,
                            OpeningCrawl = "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space...",
                            Title = "The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 3,
                            EpisodeId = 6,
                            OpeningCrawl = "Luke Skywalker has returned to\r\nhis home planet of Tatooine in\r\nan attempt to rescue his\r\nfriend Han Solo from the\r\nclutches of the vile gangster\r\nJabba the Hutt.\r\n\r\nLittle does Luke know that the\r\nGALACTIC EMPIRE has secretly\r\nbegun construction on a new\r\narmored space station even\r\nmore powerful than the first\r\ndreaded Death Star.\r\n\r\nWhen completed, this ultimate\r\nweapon will spell certain doom\r\nfor the small band of rebels\r\nstruggling to restore freedom\r\nto the galaxy...",
                            Title = "Return of the Jedi"
                        },
                        new
                        {
                            Id = 4,
                            EpisodeId = 1,
                            OpeningCrawl = "Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....",
                            Title = "The Phantom Menace"
                        },
                        new
                        {
                            Id = 5,
                            EpisodeId = 2,
                            OpeningCrawl = "There is unrest in the Galactic\r\nSenate. Several thousand solar\r\nsystems have declared their\r\nintentions to leave the Republic.\r\n\r\nThis separatist movement,\r\nunder the leadership of the\r\nmysterious Count Dooku, has\r\nmade it difficult for the limited\r\nnumber of Jedi Knights to maintain \r\npeace and order in the galaxy.\r\n\r\nSenator Amidala, the former\r\nQueen of Naboo, is returning\r\nto the Galactic Senate to vote\r\non the critical issue of creating\r\nan ARMY OF THE REPUBLIC\r\nto assist the overwhelmed\r\nJedi....",
                            Title = "Attack of the Clones"
                        },
                        new
                        {
                            Id = 6,
                            EpisodeId = 3,
                            OpeningCrawl = "War! The Republic is crumbling\r\nunder attacks by the ruthless\r\nSith Lord, Count Dooku.\r\nThere are heroes on both sides.\r\nEvil is everywhere.\r\n\r\nIn a stunning move, the\r\nfiendish droid leader, General\r\nGrievous, has swept into the\r\nRepublic capital and kidnapped\r\nChancellor Palpatine, leader of\r\nthe Galactic Senate.\r\n\r\nAs the Separatist Droid Army\r\nattempts to flee the besieged\r\ncapital with their valuable\r\nhostage, two Jedi Knights lead a\r\ndesperate mission to rescue the\r\ncaptive Chancellor....",
                            Title = "Revenge of the Sith"
                        });
                });

            modelBuilder.Entity("API.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Luke Skywalker"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C-3PO"
                        },
                        new
                        {
                            Id = 3,
                            Name = "R2-D2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Darth Vader"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Leia Organa"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Owen Lars"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beru Whitesun lars"
                        },
                        new
                        {
                            Id = 8,
                            Name = "R5-D4"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Biggs Darklighter"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Obi-Wan Kenobi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Anakin Skywalker"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Wilhuff Tarkin"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Chewbacca"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Han Solo"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Greedo"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Jabba Desilijic Tiure"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Wedge Antilles"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Jek Tono Porkins"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Yoda"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Palpatine"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Boba Fett"
                        },
                        new
                        {
                            Id = 23,
                            Name = "IG-88"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bossk"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Lando Calrissian"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Lobot"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Ackbar"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Mon Mothma"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Arvel Crynyd"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Wicket Systri Warrick"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Nien Nunb"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Qui-Gon Jinn"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Nute Gunray"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Finis Valorum"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Padmé Amidala"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Jar Jar Binks"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Roos Tarpals"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Rugor Nass"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ric Olié"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Watto"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Sebulba"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Quarsh Panaka"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Shmi Skywalker"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Darth Maul"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Bib Fortuna"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ayla Secura"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Ratts Tyerel"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dud Bolt"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Gasgano"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ben Quadinaros"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Mace Windu"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ki-Adi-Mundi"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Kit Fisto"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Eeth Koth"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Adi Gallia"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Saesee Tiin"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Yarael Poof"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Plo Koon"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Mas Amedda"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Gregar Typho"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Cordé"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Cliegg Lars"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Poggle the Lesser"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Luminara Unduli"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Barriss Offee"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Dormé"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Dooku"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Bail Prestor Organa"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Jango Fett"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Zam Wesell"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Dexter Jettster"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Lama Su"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Taun We"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Jocasta Nu"
                        },
                        new
                        {
                            Id = 75,
                            Name = "LR4-P17"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Wat Tambor"
                        },
                        new
                        {
                            Id = 77,
                            Name = "San Hill"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Shaak Ti"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Grievous"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Tarfful"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Raymus Antilles"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Sly Moore"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Tion Medon"
                        });
                });

            modelBuilder.Entity("API.Entities.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cargo_capacity");

                    b.Property<string>("Consumables")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cost_in_credits");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crew")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("HyperdriveRating")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hyperdrive_rating");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("MGLT")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "MGLT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "max_atmosphering_speed");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passengers")
                        .HasColumnType("TEXT");

                    b.Property<string>("StarshipClass")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "starship_class");

                    b.HasKey("Id");

                    b.ToTable("Starships");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CargoCapacity = "3000000",
                            Consumables = "1 year",
                            CostInCredits = "3500000",
                            Created = new DateTime(2014, 12, 10, 14, 20, 33, 369, DateTimeKind.Unspecified),
                            Crew = "30-165",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 867, DateTimeKind.Unspecified),
                            HyperdriveRating = "2.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/2.jpeg",
                            Length = "150",
                            MGLT = "60",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxAtmospheringSpeed = "950",
                            Model = "CR90 corvette",
                            Name = "CR90 corvette",
                            Passengers = "600",
                            StarshipClass = "corvette"
                        },
                        new
                        {
                            Id = 3,
                            CargoCapacity = "36000000",
                            Consumables = "2 years",
                            CostInCredits = "150000000",
                            Created = new DateTime(2014, 12, 10, 15, 8, 19, 848, DateTimeKind.Unspecified),
                            Crew = "47,060",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 870, DateTimeKind.Unspecified),
                            HyperdriveRating = "2.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/3.jpeg",
                            Length = "1,600",
                            MGLT = "60",
                            Manufacturer = "Kuat Drive Yards",
                            MaxAtmospheringSpeed = "975",
                            Model = "Imperial I-class Star Destroyer",
                            Name = "Star Destroyer",
                            Passengers = "n/a",
                            StarshipClass = "Star Destroyer"
                        },
                        new
                        {
                            Id = 5,
                            CargoCapacity = "180000",
                            Consumables = "1 month",
                            CostInCredits = "240000",
                            Created = new DateTime(2014, 12, 10, 15, 48, 0, 586, DateTimeKind.Unspecified),
                            Crew = "5",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 873, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/5.jpeg",
                            Length = "38",
                            MGLT = "70",
                            Manufacturer = "Sienar Fleet Systems, Cyngus Spaceworks",
                            MaxAtmospheringSpeed = "1000",
                            Model = "Sentinel-class landing craft",
                            Name = "Sentinel-class landing craft",
                            Passengers = "75",
                            StarshipClass = "landing craft"
                        },
                        new
                        {
                            Id = 9,
                            CargoCapacity = "1000000000000",
                            Consumables = "3 years",
                            CostInCredits = "1000000000000",
                            Created = new DateTime(2014, 12, 10, 16, 36, 50, 509, DateTimeKind.Unspecified),
                            Crew = "342,953",
                            Edited = new DateTime(2014, 12, 20, 21, 26, 24, 783, DateTimeKind.Unspecified),
                            HyperdriveRating = "4.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/9.jpeg",
                            Length = "120000",
                            MGLT = "10",
                            Manufacturer = "Imperial Department of Military Research, Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "DS-1 Orbital Battle Station",
                            Name = "Death Star",
                            Passengers = "843,342",
                            StarshipClass = "Deep Space Mobile Battlestation"
                        },
                        new
                        {
                            Id = 10,
                            CargoCapacity = "100000",
                            Consumables = "2 months",
                            CostInCredits = "100000",
                            Created = new DateTime(2014, 12, 10, 16, 59, 45, 94, DateTimeKind.Unspecified),
                            Crew = "4",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 880, DateTimeKind.Unspecified),
                            HyperdriveRating = "0.5",
                            Image = "https://starships.blob.core.windows.net/starship-api/10.jpeg",
                            Length = "34.37",
                            MGLT = "75",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxAtmospheringSpeed = "1050",
                            Model = "YT-1300 light freighter",
                            Name = "Millennium Falcon",
                            Passengers = "6",
                            StarshipClass = "Light freighter"
                        },
                        new
                        {
                            Id = 11,
                            CargoCapacity = "110",
                            Consumables = "1 week",
                            CostInCredits = "134999",
                            Created = new DateTime(2014, 12, 12, 11, 0, 39, 817, DateTimeKind.Unspecified),
                            Crew = "2",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 883, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/11.jpeg",
                            Length = "14",
                            MGLT = "80",
                            Manufacturer = "Koensayr Manufacturing",
                            MaxAtmospheringSpeed = "1000km",
                            Model = "BTL Y-wing",
                            Name = "Y-wing",
                            Passengers = "0",
                            StarshipClass = "assault starfighter"
                        },
                        new
                        {
                            Id = 12,
                            CargoCapacity = "110",
                            Consumables = "1 week",
                            CostInCredits = "149999",
                            Created = new DateTime(2014, 12, 12, 11, 19, 5, 340, DateTimeKind.Unspecified),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 886, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/12.jpeg",
                            Length = "12.5",
                            MGLT = "100",
                            Manufacturer = "Incom Corporation",
                            MaxAtmospheringSpeed = "1050",
                            Model = "T-65 X-wing",
                            Name = "X-wing",
                            Passengers = "0",
                            StarshipClass = "Starfighter"
                        },
                        new
                        {
                            Id = 13,
                            CargoCapacity = "150",
                            Consumables = "5 days",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 12, 11, 21, 32, 991, DateTimeKind.Unspecified),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 889, DateTimeKind.Unspecified),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/13.jpeg",
                            Length = "9.2",
                            MGLT = "105",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "1200",
                            Model = "Twin Ion Engine Advanced x1",
                            Name = "TIE Advanced x1",
                            Passengers = "0",
                            StarshipClass = "Starfighter"
                        },
                        new
                        {
                            Id = 15,
                            CargoCapacity = "250000000",
                            Consumables = "6 years",
                            CostInCredits = "1143350000",
                            Created = new DateTime(2014, 12, 15, 12, 31, 42, 547, DateTimeKind.Unspecified),
                            Crew = "279,144",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 893, DateTimeKind.Unspecified),
                            HyperdriveRating = "2.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/15.jpeg",
                            Length = "19000",
                            MGLT = "40",
                            Manufacturer = "Kuat Drive Yards, Fondor Shipyards",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "Executor-class star dreadnought",
                            Name = "Executor",
                            Passengers = "38000",
                            StarshipClass = "Star dreadnought"
                        },
                        new
                        {
                            Id = 17,
                            CargoCapacity = "19000000",
                            Consumables = "6 months",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 34, 52, 264, DateTimeKind.Utc),
                            Crew = "6",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 895, DateTimeKind.Utc),
                            HyperdriveRating = "4.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/17.jpeg",
                            Length = "90",
                            MGLT = "20",
                            Manufacturer = "Gallofree Yards, Inc.",
                            MaxAtmospheringSpeed = "650",
                            Model = "GR-75 medium transport",
                            Name = "Rebel transport",
                            Passengers = "90",
                            StarshipClass = "Medium transport"
                        },
                        new
                        {
                            Id = 21,
                            CargoCapacity = "70000",
                            Consumables = "1 month",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 13, 0, 56, 332, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 897, DateTimeKind.Utc),
                            HyperdriveRating = "3.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/21.jpeg",
                            Length = "21.5",
                            MGLT = "70",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxAtmospheringSpeed = "1000",
                            Model = "Firespray-31-class patrol and attack",
                            Name = "Slave 1",
                            Passengers = "6",
                            StarshipClass = "Patrol craft"
                        },
                        new
                        {
                            Id = 22,
                            CargoCapacity = "80000",
                            Consumables = "2 months",
                            CostInCredits = "240000",
                            Created = new DateTime(2014, 12, 15, 13, 4, 47, 235, DateTimeKind.Utc),
                            Crew = "6",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 900, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/22.jpeg",
                            Length = "20",
                            MGLT = "50",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "850",
                            Model = "Lambda-class T-4a shuttle",
                            Name = "Imperial shuttle",
                            Passengers = "20",
                            StarshipClass = "Armed government transport"
                        },
                        new
                        {
                            Id = 23,
                            CargoCapacity = "6000000",
                            Consumables = "2 years",
                            CostInCredits = "8500000",
                            Created = new DateTime(2014, 12, 15, 13, 6, 30, 813, DateTimeKind.Utc),
                            Crew = "854",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 902, DateTimeKind.Utc),
                            HyperdriveRating = "2.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/23.jpeg",
                            Length = "300",
                            MGLT = "40",
                            Manufacturer = "Kuat Drive Yards",
                            MaxAtmospheringSpeed = "800",
                            Model = "EF76 Nebulon-B escort frigate",
                            Name = "EF76 Nebulon-B escort frigate",
                            Passengers = "75",
                            StarshipClass = "Escort ship"
                        },
                        new
                        {
                            Id = 27,
                            CargoCapacity = "unknown",
                            Consumables = "2 years",
                            CostInCredits = "104000000",
                            Created = new DateTime(2014, 12, 18, 10, 54, 57, 804, DateTimeKind.Utc),
                            Crew = "5400",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 904, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/27.jpeg",
                            Length = "1200",
                            MGLT = "60",
                            Manufacturer = "Mon Calamari shipyards",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "MC80 Liberty type Star Cruiser",
                            Name = "Calamari Cruiser",
                            Passengers = "1200",
                            StarshipClass = "Star Cruiser"
                        },
                        new
                        {
                            Id = 28,
                            CargoCapacity = "40",
                            Consumables = "1 week",
                            CostInCredits = "175000",
                            Created = new DateTime(2014, 12, 18, 11, 16, 34, 542, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 907, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/28.jpeg",
                            Length = "9.6",
                            MGLT = "120",
                            Manufacturer = "Alliance Underground Engineering, Incom Corporation",
                            MaxAtmospheringSpeed = "1300",
                            Model = "RZ-1 A-wing Interceptor",
                            Name = "A-wing",
                            Passengers = "0",
                            StarshipClass = "Starfighter"
                        },
                        new
                        {
                            Id = 29,
                            CargoCapacity = "45",
                            Consumables = "1 week",
                            CostInCredits = "220000",
                            Created = new DateTime(2014, 12, 18, 11, 18, 4, 763, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 909, DateTimeKind.Utc),
                            HyperdriveRating = "2.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/29.jpeg",
                            Length = "16.9",
                            MGLT = "91",
                            Manufacturer = "Slayn & Korpil",
                            MaxAtmospheringSpeed = "950",
                            Model = "A/SF-01 B-wing starfighter",
                            Name = "B-wing",
                            Passengers = "0",
                            StarshipClass = "Assault Starfighter"
                        },
                        new
                        {
                            Id = 31,
                            CargoCapacity = "unknown",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 19, 17, 1, 31, 488, DateTimeKind.Utc),
                            Crew = "9",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 912, DateTimeKind.Utc),
                            HyperdriveRating = "2.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/31.jpeg",
                            Length = "115",
                            MGLT = "unknown",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxAtmospheringSpeed = "900",
                            Model = "Consular-class cruiser",
                            Name = "Republic Cruiser",
                            Passengers = "16",
                            StarshipClass = "Space cruiser"
                        },
                        new
                        {
                            Id = 32,
                            CargoCapacity = "4000000000",
                            Consumables = "500 days",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 19, 17, 4, 6, 323, DateTimeKind.Utc),
                            Crew = "175",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 915, DateTimeKind.Utc),
                            HyperdriveRating = "2.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/32.jpeg",
                            Length = "3170",
                            MGLT = "unknown",
                            Manufacturer = "Hoersch-Kessel Drive, Inc.",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "Lucrehulk-class Droid Control Ship",
                            Name = "Droid control ship",
                            Passengers = "139000",
                            StarshipClass = "Droid control ship"
                        },
                        new
                        {
                            Id = 39,
                            CargoCapacity = "65",
                            Consumables = "7 days",
                            CostInCredits = "200000",
                            Created = new DateTime(2014, 12, 19, 17, 39, 17, 582, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 917, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/39.jpeg",
                            Length = "11",
                            MGLT = "unknown",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps",
                            MaxAtmospheringSpeed = "1100",
                            Model = "N-1 starfighter",
                            Name = "Naboo fighter",
                            Passengers = "0",
                            StarshipClass = "Starfighter"
                        },
                        new
                        {
                            Id = 40,
                            CargoCapacity = "unknown",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 19, 17, 45, 3, 506, DateTimeKind.Utc),
                            Crew = "8",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 919, DateTimeKind.Utc),
                            HyperdriveRating = "1.8",
                            Image = "https://starships.blob.core.windows.net/starship-api/40.jpeg",
                            Length = "76",
                            MGLT = "unknown",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
                            MaxAtmospheringSpeed = "920",
                            Model = "J-type 327 Nubian royal starship",
                            Name = "Naboo Royal Starship",
                            Passengers = "unknown",
                            StarshipClass = "yacht"
                        },
                        new
                        {
                            Id = 41,
                            CargoCapacity = "2500000",
                            Consumables = "30 days",
                            CostInCredits = "55000000",
                            Created = new DateTime(2014, 12, 20, 9, 39, 56, 116, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 922, DateTimeKind.Utc),
                            HyperdriveRating = "1.5",
                            Image = "https://starships.blob.core.windows.net/starship-api/41.jpeg",
                            Length = "26.5",
                            MGLT = "unknown",
                            Manufacturer = "Republic Sienar Systems",
                            MaxAtmospheringSpeed = "1180",
                            Model = "Star Courier",
                            Name = "Scimitar",
                            Passengers = "6",
                            StarshipClass = "Space Transport"
                        },
                        new
                        {
                            Id = 43,
                            CargoCapacity = "unknown",
                            Consumables = "1 year",
                            CostInCredits = "2000000",
                            Created = new DateTime(2014, 12, 20, 11, 5, 51, 237, DateTimeKind.Utc),
                            Crew = "5",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 925, DateTimeKind.Utc),
                            HyperdriveRating = "0.7",
                            Image = "https://starships.blob.core.windows.net/starship-api/43.jpeg",
                            Length = "39",
                            MGLT = "unknown",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
                            MaxAtmospheringSpeed = "2000",
                            Model = "J-type diplomatic barge",
                            Name = "J-type diplomatic barge",
                            Passengers = "10",
                            StarshipClass = "Diplomatic barge"
                        },
                        new
                        {
                            Id = 47,
                            CargoCapacity = "unknown",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 20, 17, 24, 23, 509, DateTimeKind.Utc),
                            Crew = "unknown",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 928, DateTimeKind.Utc),
                            HyperdriveRating = "unknown",
                            Image = "https://starships.blob.core.windows.net/starship-api/47.jpeg",
                            Length = "390",
                            MGLT = "unknown",
                            Manufacturer = "Botajef Shipyards",
                            MaxAtmospheringSpeed = "unknown",
                            Model = "Botajef AA-9 Freighter-Liner",
                            Name = "AA-9 Coruscant freighter",
                            Passengers = "30000",
                            StarshipClass = "freighter"
                        },
                        new
                        {
                            Id = 48,
                            CargoCapacity = "60",
                            Consumables = "7 days",
                            CostInCredits = "180000",
                            Created = new DateTime(2014, 12, 20, 17, 35, 23, 906, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 930, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/48.jpeg",
                            Length = "8",
                            MGLT = "unknown",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxAtmospheringSpeed = "1150",
                            Model = "Delta-7 Aethersprite-class interceptor",
                            Name = "Jedi starfighter",
                            Passengers = "0",
                            StarshipClass = "Starfighter"
                        },
                        new
                        {
                            Id = 49,
                            CargoCapacity = "unknown",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 20, 17, 46, 46, 847, DateTimeKind.Utc),
                            Crew = "4",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 932, DateTimeKind.Utc),
                            HyperdriveRating = "0.9",
                            Image = "https://starships.blob.core.windows.net/starship-api/49.jpeg",
                            Length = "47.9",
                            MGLT = "unknown",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps",
                            MaxAtmospheringSpeed = "8000",
                            Model = "H-type Nubian yacht",
                            Name = "H-type Nubian yacht",
                            Passengers = "unknown",
                            StarshipClass = "yacht"
                        },
                        new
                        {
                            Id = 52,
                            CargoCapacity = "11250000",
                            Consumables = "2 years",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 20, 18, 8, 42, 926, DateTimeKind.Utc),
                            Crew = "700",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 935, DateTimeKind.Utc),
                            HyperdriveRating = "0.6",
                            Image = "https://starships.blob.core.windows.net/starship-api/52.jpeg",
                            Length = "752",
                            MGLT = "unknown",
                            Manufacturer = "Rothana Heavy Engineering",
                            MaxAtmospheringSpeed = "unknown",
                            Model = "Acclamator I-class assault ship",
                            Name = "Republic Assault ship",
                            Passengers = "16000",
                            StarshipClass = "assault ship"
                        },
                        new
                        {
                            Id = 58,
                            CargoCapacity = "240",
                            Consumables = "7 days",
                            CostInCredits = "35700",
                            Created = new DateTime(2014, 12, 20, 18, 37, 56, 969, DateTimeKind.Utc),
                            Crew = "3",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 937, DateTimeKind.Utc),
                            HyperdriveRating = "1.5",
                            Image = "https://starships.blob.core.windows.net/starship-api/58.jpeg",
                            Length = "15.2",
                            MGLT = "unknown",
                            Manufacturer = "Huppla Pasa Tisc Shipwrights Collective",
                            MaxAtmospheringSpeed = "1600",
                            Model = "Punworcca 116-class interstellar sloop",
                            Name = "Solar Sailer",
                            Passengers = "11",
                            StarshipClass = "yacht"
                        },
                        new
                        {
                            Id = 59,
                            CargoCapacity = "50000000",
                            Consumables = "4 years",
                            CostInCredits = "125000000",
                            Created = new DateTime(2014, 12, 20, 19, 40, 21, 902, DateTimeKind.Utc),
                            Crew = "600",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 941, DateTimeKind.Utc),
                            HyperdriveRating = "1.5",
                            Image = "https://starships.blob.core.windows.net/starship-api/59.jpeg",
                            Length = "1088",
                            MGLT = "unknown",
                            Manufacturer = "Rendili StarDrive, Free Dac Volunteers Engineering corps.",
                            MaxAtmospheringSpeed = "1050",
                            Model = "Providence-class carrier/destroyer",
                            Name = "Trade Federation cruiser",
                            Passengers = "48247",
                            StarshipClass = "capital ship"
                        },
                        new
                        {
                            Id = 61,
                            CargoCapacity = "50000",
                            Consumables = "56 days",
                            CostInCredits = "1000000",
                            Created = new DateTime(2014, 12, 20, 19, 48, 40, 409, DateTimeKind.Utc),
                            Crew = "5",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 944, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/61.jpeg",
                            Length = "18.5",
                            MGLT = "unknown",
                            Manufacturer = "Cygnus Spaceworks",
                            MaxAtmospheringSpeed = "2000",
                            Model = "Theta-class T-2c shuttle",
                            Name = "Theta-class T-2c shuttle",
                            Passengers = "16",
                            StarshipClass = "transport"
                        },
                        new
                        {
                            Id = 63,
                            CargoCapacity = "20000000",
                            Consumables = "2 years",
                            CostInCredits = "59000000",
                            Created = new DateTime(2014, 12, 20, 19, 52, 56, 232, DateTimeKind.Utc),
                            Crew = "7400",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 946, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/63.jpeg",
                            Length = "1137",
                            MGLT = "unknown",
                            Manufacturer = "Kuat Drive Yards, Allanteen Six shipyards",
                            MaxAtmospheringSpeed = "975",
                            Model = "Senator-class Star Destroyer",
                            Name = "Republic attack cruiser",
                            Passengers = "2000",
                            StarshipClass = "star destroyer"
                        },
                        new
                        {
                            Id = 64,
                            CargoCapacity = "unknown",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 20, 19, 55, 15, 396, DateTimeKind.Utc),
                            Crew = "3",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 948, DateTimeKind.Utc),
                            HyperdriveRating = "0.5",
                            Image = "https://starships.blob.core.windows.net/starship-api/64.jpeg",
                            Length = "29.2",
                            MGLT = "unknown",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated",
                            MaxAtmospheringSpeed = "1050",
                            Model = "J-type star skiff",
                            Name = "Naboo star skiff",
                            Passengers = "3",
                            StarshipClass = "yacht"
                        },
                        new
                        {
                            Id = 65,
                            CargoCapacity = "60",
                            Consumables = "2 days",
                            CostInCredits = "320000",
                            Created = new DateTime(2014, 12, 20, 19, 56, 57, 468, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 951, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/65.jpeg",
                            Length = "5.47",
                            MGLT = "unknown",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxAtmospheringSpeed = "1500",
                            Model = "Eta-2 Actis-class light interceptor",
                            Name = "Jedi Interceptor",
                            Passengers = "0",
                            StarshipClass = "starfighter"
                        },
                        new
                        {
                            Id = 66,
                            CargoCapacity = "110",
                            Consumables = "5 days",
                            CostInCredits = "155000",
                            Created = new DateTime(2014, 12, 20, 20, 3, 48, 603, DateTimeKind.Utc),
                            Crew = "3",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 953, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/66.jpeg",
                            Length = "14.5",
                            MGLT = "100",
                            Manufacturer = "Incom Corporation, Subpro Corporation",
                            MaxAtmospheringSpeed = "1000",
                            Model = "Aggressive Reconnaissance-170 starfighte",
                            Name = "arc-170",
                            Passengers = "0",
                            StarshipClass = "starfighter"
                        },
                        new
                        {
                            Id = 68,
                            CargoCapacity = "40000000",
                            Consumables = "2 years",
                            CostInCredits = "57000000",
                            Created = new DateTime(2014, 12, 20, 20, 7, 11, 538, DateTimeKind.Utc),
                            Crew = "200",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 956, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/68.jpeg",
                            Length = "825",
                            MGLT = "unknown",
                            Manufacturer = "Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries",
                            MaxAtmospheringSpeed = "unknown",
                            Model = "Munificent-class star frigate",
                            Name = "Banking clan frigte",
                            Passengers = "unknown",
                            StarshipClass = "cruiser"
                        },
                        new
                        {
                            Id = 74,
                            CargoCapacity = "140",
                            Consumables = "7 days",
                            CostInCredits = "168000",
                            Created = new DateTime(2014, 12, 20, 20, 38, 5, 31, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 959, DateTimeKind.Utc),
                            HyperdriveRating = "6",
                            Image = "https://starships.blob.core.windows.net/starship-api/74.jpeg",
                            Length = "6.71",
                            MGLT = "unknown",
                            Manufacturer = "Feethan Ottraw Scalable Assemblies",
                            MaxAtmospheringSpeed = "1100",
                            Model = "Belbullab-22 starfighter",
                            Name = "Belbullab-22 starfighter",
                            Passengers = "0",
                            StarshipClass = "starfighter"
                        },
                        new
                        {
                            Id = 75,
                            CargoCapacity = "60",
                            Consumables = "15 hours",
                            CostInCredits = "102500",
                            Created = new DateTime(2014, 12, 20, 20, 43, 4, 349, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 961, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Image = "https://starships.blob.core.windows.net/starship-api/75.jpeg",
                            Length = "7.9",
                            MGLT = "unknown",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxAtmospheringSpeed = "1050",
                            Model = "Alpha-3 Nimbus-class V-wing starfighter",
                            Name = "V-wing",
                            Passengers = "0",
                            StarshipClass = "starfighter"
                        });
                });

            modelBuilder.Entity("FilmStarship", b =>
                {
                    b.Property<int>("FilmsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarshipsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmsId", "StarshipsId");

                    b.HasIndex("StarshipsId");

                    b.ToTable("FilmStarship");
                });

            modelBuilder.Entity("PersonStarship", b =>
                {
                    b.Property<int>("PilotsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarshipsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PilotsId", "StarshipsId");

                    b.HasIndex("StarshipsId");

                    b.ToTable("PersonStarship");
                });

            modelBuilder.Entity("FilmStarship", b =>
                {
                    b.HasOne("API.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Starship", null)
                        .WithMany()
                        .HasForeignKey("StarshipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonStarship", b =>
                {
                    b.HasOne("API.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PilotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Starship", null)
                        .WithMany()
                        .HasForeignKey("StarshipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
