namespace API.Entities
{
    public class SeedPeople
    {
        public static Person[] Load() => new Person[] {
            new Person { Id = 1, Name = "Luke Skywalker" },
            new Person { Id = 2, Name = "C-3PO" },
            new Person { Id = 3, Name = "R2-D2" },
            new Person { Id = 4, Name = "Darth Vader" },
            new Person { Id = 5, Name = "Leia Organa" },
            new Person { Id = 6, Name = "Owen Lars" },
            new Person { Id = 7, Name = "Beru Whitesun lars" },
            new Person { Id = 8, Name = "R5-D4" },
            new Person { Id = 9, Name = "Biggs Darklighter" },
            new Person { Id = 10, Name = "Obi-Wan Kenobi" },
            new Person { Id = 11, Name = "Anakin Skywalker" },
            new Person { Id = 12, Name = "Wilhuff Tarkin" },
            new Person { Id = 13, Name = "Chewbacca" },
            new Person { Id = 14, Name = "Han Solo" },
            new Person { Id = 15, Name = "Greedo" },
            new Person { Id = 16, Name = "Jabba Desilijic Tiure" },
            new Person { Id = 18, Name = "Wedge Antilles" },
            new Person { Id = 19, Name = "Jek Tono Porkins" },
            new Person { Id = 20, Name = "Yoda" },
            new Person { Id = 21, Name = "Palpatine" },
            new Person { Id = 22, Name = "Boba Fett" },
            new Person { Id = 23, Name = "IG-88" },
            new Person { Id = 24, Name = "Bossk" },
            new Person { Id = 25, Name = "Lando Calrissian" },
            new Person { Id = 26, Name = "Lobot" },
            new Person { Id = 27, Name = "Ackbar" },
            new Person { Id = 28, Name = "Mon Mothma" },
            new Person { Id = 29, Name = "Arvel Crynyd" },
            new Person { Id = 30, Name = "Wicket Systri Warrick" },
            new Person { Id = 31, Name = "Nien Nunb" },
            new Person { Id = 32, Name = "Qui-Gon Jinn" },
            new Person { Id = 33, Name = "Nute Gunray" },
            new Person { Id = 34, Name = "Finis Valorum" },
            new Person { Id = 35, Name = "Padmé Amidala" },
            new Person { Id = 36, Name = "Jar Jar Binks" },
            new Person { Id = 37, Name = "Roos Tarpals" },
            new Person { Id = 38, Name = "Rugor Nass" },
            new Person { Id = 39, Name = "Ric Olié" },
            new Person { Id = 40, Name = "Watto" },
            new Person { Id = 41, Name = "Sebulba" },
            new Person { Id = 42, Name = "Quarsh Panaka" },
            new Person { Id = 43, Name = "Shmi Skywalker" },
            new Person { Id = 44, Name = "Darth Maul" },
            new Person { Id = 45, Name = "Bib Fortuna" },
            new Person { Id = 46, Name = "Ayla Secura" },
            new Person { Id = 47, Name = "Ratts Tyerel" },
            new Person { Id = 48, Name = "Dud Bolt" },
            new Person { Id = 49, Name = "Gasgano" },
            new Person { Id = 50, Name = "Ben Quadinaros" },
            new Person { Id = 51, Name = "Mace Windu" },
            new Person { Id = 52, Name = "Ki-Adi-Mundi" },
            new Person { Id = 53, Name = "Kit Fisto" },
            new Person { Id = 54, Name = "Eeth Koth" },
            new Person { Id = 55, Name = "Adi Gallia" },
            new Person { Id = 56, Name = "Saesee Tiin" },
            new Person { Id = 57, Name = "Yarael Poof" },
            new Person { Id = 58, Name = "Plo Koon" },
            new Person { Id = 59, Name = "Mas Amedda" },
            new Person { Id = 60, Name = "Gregar Typho" },
            new Person { Id = 61, Name = "Cordé" },
            new Person { Id = 62, Name = "Cliegg Lars" },
            new Person { Id = 63, Name = "Poggle the Lesser" },
            new Person { Id = 64, Name = "Luminara Unduli" },
            new Person { Id = 65, Name = "Barriss Offee" },
            new Person { Id = 66, Name = "Dormé" },
            new Person { Id = 67, Name = "Dooku" },
            new Person { Id = 68, Name = "Bail Prestor Organa" },
            new Person { Id = 69, Name = "Jango Fett" },
            new Person { Id = 70, Name = "Zam Wesell" },
            new Person { Id = 71, Name = "Dexter Jettster" },
            new Person { Id = 72, Name = "Lama Su" },
            new Person { Id = 73, Name = "Taun We" },
            new Person { Id = 74, Name = "Jocasta Nu" },
            new Person { Id = 75, Name = "LR4-P17" },
            new Person { Id = 76, Name = "Wat Tambor" },
            new Person { Id = 77, Name = "San Hill" },
            new Person { Id = 78, Name = "Shaak Ti" },
            new Person { Id = 79, Name = "Grievous" },
            new Person { Id = 80, Name = "Tarfful" },
            new Person { Id = 81, Name = "Raymus Antilles" },
            new Person { Id = 82, Name = "Sly Moore" },
            new Person { Id = 83, Name = "Tion Medon" }
        };
    }
}